name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black
        run: black --exclude=/data_sources--check .

      - name: Run Flake8
        run: flake8 .

      - name: Run Tests
        run: pytest

      - name: Build Documentation
        run: |
          cd docs
          make html
